server:
  port: 3002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaomi?serverTimezone=UTC
    username: root
    password: 203619
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
